font=CodeNewRoman Nerd Font Mono:size=12
selection-target=both
[main]
include=~/.config/foot/themes/noctalia
include=~/.config/foot/colors.ini
[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
# vim: ft=dosini
