conky.config = {
	out_to_x = false, -- 关闭X11输出
	out_to_wayland = true, -- 开启Wayland输出
	own_window = false, -- 创建独立窗口
	own_window_type = "normal",
	wayland_position = "top_left",
	minimum_height = 100,
	minimum_width = 5,
	-- wayland_margin_h = 20,          -- 水平边距
	-- wayland_margin_v = 20,          -- 垂直边距
	own_window_argb_visual = true, -- 启用透明
	own_window_argb_value = 150, -- 透明度
}

conky.text = [[
${color white}${font sans:size=12}${time %H:%M:%S}${font}
${color lightgrey}CPU: ${cpu}%${color}\
${color lightgrey}MEM: $memperc%${color}\
]]
