# --- Main Colors ---
background            #101418
foreground            #e0e2e8
cursor                #e0e2e8
cursor_text_color     #101418

selection_background  #3a4857
selection_foreground  #d5e4f7

url_color             #d4bee6

# --- ANSI Colors ---
color0                #101418
color1                #ffb4ab
color2                #d4bee6
color3                #b9c8da
color4                #9ccbfb
color5                #d4bee6
color6                #b9c8da
color7                #e0e2e8

color8                #42474e
color9                #93000a
color10               #504061
color11               #3a4857
color12               #104a73
color13               #3a4857
color14               #504061
color15               #c2c7cf

# --- Starship Prompt Bubbles ---
color255              #104a73
color254              #9ccbfb
color253              #3a4857
color252              #b9c8da
color251              #504061
color250              #d4bee6
color249              #93000a
color248              #ffb4ab

color232              #cfe5ff
color233              #003354
color234              #d5e4f7
color235              #243240
color236              #efdbff
color237              #392a49
color238              #ffdad6
color239              #690005
color240              #cfe5ff

# Matched with unthemed light/dark
color243              #9ccbfb
color244              #ffb4ab
color245              #42474e

# --- UI Elements ---
active_tab_foreground   #003354
active_tab_background   #9ccbfb
inactive_tab_foreground #cfe5ff
inactive_tab_background #104a73

active_border_color     #9ccbfb
inactive_border_color   #8c9199

# --- Marks ---
mark1_foreground        #001d33
mark1_background        #cfe5ff
mark2_foreground        #0e1d2a
mark2_background        #d5e4f7
mark3_foreground        #231533
mark3_background        #efdbff
