gui:
  theme:
    activeBorderColor:
      - "#67a8e4"
      - bold
    inactiveBorderColor:
      - "#5c5ed6"
    searchingActiveBorderColor:
      - "#9762d0"
      - bold
    optionsTextColor:
      - "#afb3b6"
    selectedLineBgColor:
      - "#afb3b6"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#afb3b6"
    cherryPickedCommitBgColor:
      - "#9762d0"
    markedBaseCommitFgColor:
      - "#9762d0"
    markedBaseCommitBgColor:
      - "#fd4663"
    unstagedChangesColor:
      - "#fd4663"
    defaultFgColor:
      - "#f2f2f3"
