db_path = "~/.local/share/markerss/markerss.db"
cache_ttl_days = 7
# export_dir = "/data/out"
fetch_timeout = 30
# max_items_per_feed = 50
# browser = "firefox"
refresh = true
# refresh = { interval_minutes = 30 }
pane_ratio = [0.15, 0.25, 0.6]
nav_presets = [
  [
    "Favourite",
    "Feeds",
  ],
  [
    "Categories",
    "Tags",
    "Unread",
    "Read Later",
    "Saved",
  ]
]
background = "dark"
theme = "nord.toml"
foldlevel = 0
sort = ["time","title"]
# reading_width = 80

[markers]
saved = ""
later = ""
favourite = ""
lazy = "󰒲"
