include splits.conf
font_family      CodeNewRoman Nerd Font Mono
italic_font      IBM Plex Mono
bold_font        DaddyTimeMono Nerd Font
bold_italic_font Monaco Nerd Font Mono
font_size 12.0
disable_ligatures cursor
cursor none
mouse_hide_wait -1
detect_urls yes
show_hyperlink_targets yes
underline_hyperlinks always
copy_on_select yes
enabled_layouts splits,tall,grid,stack
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
shell_integration no-title
map page_up scroll_page_up
map page_down scroll_page_up
map ctrl+equal       change_font_size all +2.0
map ctrl+minus       change_font_size all -2.0
include themes/noctalia.conf
